# -*- coding: utf-8 -*-
"""Datavisualisasi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LAxHfU_-URSUWu1GkEUyvu-3h_nFPSa2
"""

import pandas as pd
df = pd.read_csv('/content/Most-Popular-Programming-Languages-from-2004-to-2022.csv', encoding='utf-8')
# Mengubah Date dari format text ke format tanggal
df['Date'] = pd.to_datetime(df['Date'])

df
df['Python']
df.describe()
df.info()
df.head()
df.tail()

# merepresentasikan data menjadi garis linear dalam grafik
# label berfungsi agar dapat dikenali legends
plt.plot(df['Date'], df['Python'], label='Python')
plt.plot(df['Date'], df['JavaScript'], label='JavaScript')
plt.plot(df['Date'], df['Kotlin'], label='Kotlin')
plt.plot(df['Date'], df['Swift'], label='Swift')

plt.xlabel('Tahun') # informasi teks untuk axis horizontal
plt.ylabel('Popularitas (%)') # informasi teks untuk axis vertikal
plt.title('Perkembangan popularitas bahasa pemrograman') # judul
plt.grid(True) # garis background untuk mempermudah pembacaan
plt.legend() # informasi warna garis